export default function ContentSections() {
  return (
    <>
      <section className="content-section how-it-works">
        <h2>How Our Password Generator Creates Strong, Secure Passwords</h2>
        
        <div className="quick-answer">
          <h3>Quick Answer</h3>
          <p>Our password generator uses your browser's built-in Web Crypto API (<code>crypto.getRandomValues()</code>) to create cryptographically secure random passwords. This is the same military-grade technology that protects banking transactions, ensuring genuinely unpredictable passwords with no server transmission—everything happens locally on your device.</p>
        </div>
        
        <p>
          Unlike basic <strong>password generators</strong> that use simple randomization, our tool taps into your browser's built-in cryptographic engine (<code>crypto.getRandomValues()</code>). Think of it like this: we're using the same military-grade randomness that protects your banking data to create your passwords. No predictable patterns, no guessable sequences—just genuinely <strong>random passwords</strong> that even the most sophisticated hackers can't crack.
        </p>
        <p>
          What makes us different? We show you the math. Every time you <strong>generate a password</strong>, you'll see its strength score, entropy level (how much randomness it contains), and an estimate of how long it would take modern computers to crack it. It's like having a security expert explain why your password is unbreakable—except it happens instantly.
        </p>
        
        <h3>Security Features That Actually Matter</h3>
        <ul>
          <li>
            <strong>Real-Time Strength Analysis:</strong> Watch your <strong>password strength</strong> update live as you adjust settings. Our meter uses the same calculations recommended by cybersecurity experts, so you know exactly how protected you are—no guessing.
          </li>
          <li>
            <strong>Entropy Explained Simply:</strong> We calculate the mathematical "randomness" of your <strong>secure password</strong>. Higher entropy means more possible combinations, which means it's exponentially harder for attackers to crack. We show you this number so you understand why a 16-character password is thousands of times stronger than an 8-character one.
          </li>
          <li>
            <strong>Crack Time You Can Actually Understand:</strong> Instead of technical jargon, we tell you: "This password would take 1 million years to crack" or "2 centuries." That's way more useful than "128-bit encryption," right? These estimates assume an attacker making 10 billion guesses per second—which is what modern hacking tools can do.
          </li>
          <li>
            <strong>Your Last 5 Passwords (Temporarily):</strong> Need to compare a few options? Your <strong>password history</strong> shows your last 5 generated passwords—but only while you're on the page. Close your browser, and they're gone forever. We never store anything permanently.
          </li>
          <li>
            <strong>Full Control Over Character Types:</strong> Pick exactly what goes into your <strong>random password</strong>—uppercase, lowercase, numbers, symbols, or all four. Some sites don't allow certain symbols? No problem. Need to exclude confusing characters like "O" and "0"? We've got you covered.
          </li>
          <li>
            <strong>Everything Stays On Your Device:</strong> Here's the most important part: your passwords never leave your browser. Not to our servers, not to Google, nowhere. All <strong>password generation</strong> happens locally on your device using JavaScript. We literally can't see your passwords even if we wanted to. Your security is in your hands—literally.
          </li>
        </ul>
        
        <h3>NIST 2025 Compliance</h3>
        <p>
          Our password generator follows <strong>NIST SP 800-63B</strong> (2025 revision) guidelines for authentication and password management. This includes support for 8-64 character lengths, all Unicode characters, no forced composition rules, and no mandatory periodic password changes. We align with federal cybersecurity standards to ensure your passwords meet government-grade security requirements.
        </p>
      </section>

      <section className="content-section security-tips" id="security-tips">
        <h2>7 Password Security Tips That Actually Work in 2025</h2>
        
        <div className="quick-answer">
          <h3>Quick Answer</h3>
          <p>The most effective password security in 2025: use unique 16+ character passwords for every account (generated by tools like ours), store them in a password manager, enable two-factor authentication everywhere, and only change passwords when there's a confirmed breach—not on arbitrary schedules.</p>
        </div>
        
        <p>
          Let's be honest: creating <strong>strong passwords</strong> sounds boring until your account gets hacked. The good news? Protecting yourself doesn't have to be complicated. Follow these expert-backed strategies, and you'll be more secure than 95% of internet users. No technical degree required.
        </p>
        
        <h3>1. Use a Different Password for Every Account—Seriously</h3>
        <p>
          This is the golden rule that most people ignore. Here's why it matters: when hackers breach a website (and they do constantly), they immediately try those stolen passwords on every other major site—banking, email, social media, everything. It's called "credential stuffing," and it works because people reuse passwords everywhere. Use our <strong>password generator</strong> to create a unique password for every single account. Yes, every one.
        </p>
        
        <h3>2. Make It at Least 16 Characters Long (Longer Is Better)</h3>
        <p>
          NIST—the government agency that sets cybersecurity standards—now recommends 15-16 character minimum. Why? An 8-character <strong>password</strong> can be cracked in hours with modern computers. A 16-character password? Literally centuries, even with cutting-edge hacking tools. Our generator supports up to 64 characters, so go wild. The longer your <strong>secure password</strong>, the safer you are.
        </p>
        
        <h3>3. Mix It Up: Letters, Numbers, and Symbols</h3>
        <p>
          The more variety in your <strong>random password</strong>, the harder it is to crack. Think of each character type as adding another layer of security. When you combine uppercase, lowercase, numbers, and symbols (!@#$%^&*), you're creating trillions more possible combinations. Our <strong>password strength</strong> meter shows you exactly how much stronger your password gets when you enable all character types.
        </p>
        
        <h3>4. Don't Use Personal Information (Ever)</h3>
        <p>
          Names, birthdays, pet names, addresses, phone numbers—all terrible password ingredients. Hackers start by checking these predictable choices because they work so often it's almost embarrassing. Social media makes this even easier: "JohnSmith1985" or "Fluffy2024" might seem unique to you, but they're the first things attackers try. Instead, let our tool <strong>generate secure passwords</strong> that have zero connection to your personal life.
        </p>
        
        <h3>5. Get a Password Manager (This Changes Everything)</h3>
        <p>
          Here's the problem: you need 50+ unique, complex passwords. You can't remember them all. Solution? A <strong>password manager</strong> like 1Password, NordPass, or LastPass. They store all your passwords in one encrypted vault, autofill them when you need them, and even generate new ones for you. You only need to remember one master password—that's it. NIST actually recommends this approach now. It's how security professionals protect themselves.
        </p>
        
        <h3>6. Turn On Two-Factor Authentication (2FA)</h3>
        <p>
          Even the <strong>strongest password</strong> isn't perfect. 2FA adds a second security layer—usually a code sent to your phone or generated by an app. Think of it like this: your password is the key to your house, but 2FA is the security system inside. According to Microsoft, 2FA blocks over 99% of automated attacks. Enable it everywhere you can, especially for email, banking, and social media accounts.
        </p>
        
        <h3>7. Change Passwords Only When Necessary</h3>
        <p>
          Old advice said "change your password every 90 days." New NIST guidelines? Don't bother—unless there's been a breach. Why? Forced changes lead to weak passwords (Password1, Password2, Password3...). Instead, use services like "Have I Been Pwned" to check if your accounts appear in data breaches. If they do, immediately <strong>create a new password</strong> with our generator. If not, you're good.
        </p>
        
        <p>
          Bottom line: <strong>Strong password security</strong> in 2025 means longer passwords, unique passwords for everything, and using tools (like our <strong>free password generator</strong> and a password manager) to make it easy. Do these seven things, and you'll sleep better knowing your accounts are actually protected.
        </p>
      </section>

      <section className="content-section faq-section" id="faq-section">
        <h2>Common Questions About Password Generators (Answered)</h2>
        
        <h3>Is this password generator safe to use?</h3>
        <p>
          <strong>Yes, absolutely safe.</strong> Every password you generate stays on your device. We use your browser's built-in <code>crypto.getRandomValues()</code> function—the same cryptographic system that secures online banking. Nothing gets sent to our servers, nothing gets logged, and we literally can't see what you create. Want proof? Open your browser's network tab and generate a password—you'll see zero requests to external servers.
        </p>
        
        <h3>How long should my password actually be?</h3>
        <p>
          <strong>At least 16 characters.</strong> An 8-character password might be cracked in hours with modern hacking tools. A 16-character password with mixed character types would take centuries. NIST (the cybersecurity experts who write the rules) now recommends 15-16 as the minimum. Our password generator goes up to 64 characters if you want maximum security. For everyday accounts, 16-20 characters is perfect.
        </p>
        
        <h3>What makes this generator "dynamic"?</h3>
        <p>
          <strong>Real-time feedback and full customization.</strong> We show you actual numbers: entropy (mathematical randomness), estimated crack time, and security level—not just "strong" or "weak." Watch the meter change as you adjust length or character types. Everything adapts to your needs: toggle symbols, exclude confusing characters, adjust length. Most password generators are static—you get what you get. We're dynamic—you control everything.
        </p>
        
        <h3>Can I use special characters and symbols?</h3>
        <p>
          <strong>Yes, and you should.</strong> Including symbols (!@#$%^&*) dramatically boosts password strength by adding 32 more possible characters per position, which multiplies total combinations exponentially. Some older websites reject certain symbols, so if you hit a wall, just disable the symbols option and compensate with a longer password—a 24-character letters-and-numbers password is still incredibly secure.
        </p>
        
        <h3>What if I forget my generated password?</h3>
        <p>
          <strong>Use a password manager.</strong> Workflow: 1) Use our tool to generate a secure password, 2) Immediately copy it to your password manager (1Password, NordPass, LastPass, Bitwarden), 3) Let the password manager autofill it whenever you log in. You only need to remember one master password. Our "Recent Passwords" history shows your last 5 passwords temporarily, but they disappear when you close the page—never rely on that as storage.
        </p>
        
        <h3>Are password generators better than creating my own?</h3>
        <p>
          <strong>Yes, every single time.</strong> Humans are terrible at randomness. Even when we try to be "random," we fall into predictable patterns that hackers exploit—keyboard patterns (qwerty123), repeated characters (aaa111), or sequences (abc123). A proper random password generator using cryptographic functions creates genuinely unpredictable combinations that even the smartest hacker can't guess, while automatically ensuring the right complexity.
        </p>
        
        <h3>Should I change my passwords regularly?</h3>
        <p>
          <strong>Only when necessary.</strong> NIST now says forced regular changes actually decrease security—people make weak patterns (Password1, Password2, Password3). Instead: use strong unique passwords everywhere, enable two-factor authentication, and only change passwords if there's been a data breach. Use "Have I Been Pwned" to check if your accounts appear in known breaches. When they do, generate a new password immediately.
        </p>
      </section>
    </>
  )
}